framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    #http_method_override: true

    assets:
        version: 'v1'
    #        json_manifest_path: '%kernel.root_dir%/../../asset/build/rev-manifest.json'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    ide: 'phpstorm://open?file=%%f&line=%%l&/var/www/html/>/home/u/PhpstormProjects/classifieds/'
