framework:
    messenger:
        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_close_connection

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            one_at_time: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'App\System\Messenger\Base\AsyncMessageInterface': async
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
