parameters:
    twig_date_format: 'Y-m-d, H:i'
    twig_date_format_short: 'Y-m-d'

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/form_layout.html.twig']
    date:
        format: '%twig_date_format%'
        timezone: '%timezone%'
    exception_controller: App\Exception\Controller\ExceptionController::showAction
