twig:
    globals:
        dateFormat: '%date_format%'
        dateFormatShort: '%date_format_short%'
        dateFormatYmd: 'Y-m-d'
        dateFormatYmdHis: 'Y-m-d H:i:s'
        favicon_dir: '%favicon_dir%'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/form_layout.html.twig']
    date:
        format: '%date_format%'
        timezone: '%timezone%'
    exception_controller: null
