monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [403, 404]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            include_stacktraces: true
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
