<?php

declare(strict_types=1);

use App\Helper\FilePath;
use App\Helper\Random;

if (empty($_POST)) {
    echo 'run from index.php file';
    exit;
}

require dirname(__DIR__) . '/symfony/vendor/autoload.php';

$dbName = 'dev_test';
$pdo = new \PDO("mysql:host=mysql;dbname=$dbName", 'root', '', [
    \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
    \PDO::ATTR_EMULATE_PREPARES => true,
    \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',
]);

if (countTables($dbName) > 0) {
    echo 'Database is not empty, clear it first';
    exit;
}

$pdo->beginTransaction();
try {
    loadSql(__DIR__ . '/data/_schema.sql');
    loadSql(__DIR__ . '/data/_required_data.sql');
    loadSql(__DIR__ . '/data/settings.sql');
    loadSql(__DIR__ . '/data/example/categories.sql');
} catch (\Throwable $e) {
    $pdo->rollBack();
    throw $e;
}

$pass = empty($_POST['db_pass']) ? '' : ':' . $_POST['db_pass'];

dumpConfig([
    'DATABASE_URL' => "mysql://{$_POST['db_user']}{$pass}@{$_POST['db_host']}:{$_POST['db_port']}/{$_POST['db_name']}",
]);

echo "success, remove install directory: install_MM8tHbrn";

function loadSql(string $filePath) {
    global $pdo;
    $sqlFileContent = file_get_contents($filePath);

    $stmt = $pdo->query($sqlFileContent);

    while ($stmt->nextRowset()) {
        continue;
    }
}

function countTables(string $dbName): int {
    global $pdo;

    $stmt = $pdo->prepare(
    /** @lang MySQL */ 'SELECT count(1) FROM information_schema.tables where table_schema=:dbName;'
    );
    $stmt->bindValue('dbName', $dbName);
    $stmt->execute();
    return (int) $stmt->fetchColumn();
}

function dumpConfig(array $config) {
    $defaultConfig = [
        'APP_ENV' => 'prod',
        'APP_SECRET' => Random::string(64),
        'APP_LOCALE' => 'en',
        'APP_TIMEZONE' => 'Europe/Warsaw',
        'APP_UPGRADE_DISABLED' => false,
        'APP_UPGRADE_AVAILABLE_CHECK_DISABLED' => false,
        'DATABASE_URL' => 'mysql://root@localhost:3306/classifieds',
        'MAILER_URL' => 'mysql://root@mysql:3306/dev_test',
    ];
    $configToSave = array_replace($defaultConfig, $config);
    $configPhpString = var_export($configToSave, true);

    $vars = <<<EOF
<?php

// This file was generated by running install script"

return $configPhpString;

EOF;

    file_put_contents(FilePath::getProjectDir() . '/symfony/.env.local.php', $vars, LOCK_EX);

}
