parameters:
    mailer_from_email_address: '%env(MAILER_FROM_EMAIL_ADDRESS)%'
    mailer_reply_to_address: '%env(MAILER_REPLY_TO_ADDRESS)%'
    mailer_from_name: '%env(MAILER_FROM_NAME)%'

swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
